// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckDataRequest check data request
//
// swagger:model CheckDataRequest
type CheckDataRequest struct {

	// types
	Types []string `json:"types"`
}

// Validate validates this check data request
func (m *CheckDataRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this check data request based on context it is used
func (m *CheckDataRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CheckDataRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckDataRequest) UnmarshalBinary(b []byte) error {
	var res CheckDataRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
