// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CollectJobRequest collect job request
//
// swagger:model CollectJobRequest
type CollectJobRequest struct {

	// cluster name
	ClusterName string `json:"clusterName,omitempty"`

	// collectors
	Collectors []string `json:"collectors"`

	// explain sqls
	ExplainSqls []string `json:"explain_sqls"`

	// from
	From string `json:"from,omitempty"`

	// metricfilter
	Metricfilter []string `json:"metricfilter"`

	// monitor namespace
	MonitorNamespace string `json:"monitor_namespace,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this collect job request
func (m *CollectJobRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this collect job request based on context it is used
func (m *CollectJobRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CollectJobRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CollectJobRequest) UnmarshalBinary(b []byte) error {
	var res CollectJobRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
