// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CollectJob collect job
//
// swagger:model CollectJob
type CollectJob struct {

	// cluster name
	ClusterName string `json:"clusterName,omitempty"`

	// collectors
	Collectors []string `json:"collectors"`

	// date
	Date string `json:"date,omitempty"`

	// dir
	Dir string `json:"dir,omitempty"`

	// from
	From string `json:"from,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this collect job
func (m *CollectJob) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this collect job based on context it is used
func (m *CollectJob) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CollectJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CollectJob) UnmarshalBinary(b []byte) error {
	var res CollectJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
