// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DataSet data set
//
// swagger:model DataSet
type DataSet struct {

	// cluster Id
	ClusterID int64 `json:"clusterId,omitempty"`

	// cluster name
	ClusterName string `json:"clusterName,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// size
	Size int64 `json:"size,omitempty"`
}

// Validate validates this data set
func (m *DataSet) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this data set based on context it is used
func (m *DataSet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DataSet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataSet) UnmarshalBinary(b []byte) error {
	var res DataSet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
