name = "ticdc-debug"
version = "0.0.1"
maintainers = [
  "pingcap"
]

# list of data types to collect
collectors = [
  "log",
  "config",
  "system",
  "perf",
  "debug",
  "monitor"
]

# list of component roles to collect
roles = [
  "ticdc"
]
