name = "tidb-plan-replayer"
version = "0.0.1"
maintainers = [
    "pingcap"
]

# list of data types to collect
collectors = [
    "config",
    "db_vars",
    "sql_bind",
    "plan_replayer"
]

# list of component roles to collect
roles = [
    "tidb"
]
