#!/bin/bash

grep -w tidb /etc/shadow > /dev/null
if [ $? != 0 ]; then
        useradd tidb
fi
grep -w influxdb /etc/shadow > /dev/null
if [ $? != 0 ]; then
        useradd influxdb
fi

chown -R tidb:tidb /usr/local/tidb-foresight
chown -R tidb:tidb /usr/local/prometheus
chown -R influxdb:influxdb /usr/local/influxdb
chown -R influxdb:influxdb /var/lib/influxdb

systemctl daemon-reload

echo """To start tidb-foresight (will listen on port 9527):
        systemctl start foresight-9527
        systemctl start influxd-9528
        systemctl start prometheus-9529"""
echo """Deployment directory as follows:
        /usr/local/tidb-foresight
        /usr/local/influxdb
        /usr/local/prometheus"""
echo """View the log as follows:
        journalctl -u foresight-9527
        journalctl -u influxd-9528
        journalctl -u prometheus-9529"""
