#!/bin/bash

if [ -f /etc/systemd/system/foresight-9527.service ];then
	systemctl stop foresight-9527.service
fi
if [ -f /etc/systemd/system/influxd-9528.service ];then
	systemctl stop influxd-9528.service
fi
if [ -f /etc/systemd/system/prometheus-9529.service ];then
	systemctl stop prometheus-9529.service
fi
