kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.diag.serviceAccount | default "pingcap-clinic" }}
  labels:
    app: pingcap-clinic
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.diag.clinicRole | default "pingcap-clinic" }}
  labels:
    app: pingcap-clinic
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["pingcap.com"]
    resources: ["tidbclusters", "tidbmonitors"]
    verbs: ["get", "list"]
  {{- if eq .Values.diag.tlsEnabled true}}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  {{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.diag.serviceAccount | default "pingcap-clinic" }}
roleRef:
  kind: Role
  name: {{ .Values.diag.clinicRole | default "pingcap-clinic" }}
  apiGroup: rbac.authorization.k8s.io
{{- if eq .Values.diag.clusterRoleEnabled true}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.diag.clinicRole | default "pingcap-clinic" }}
  labels:
    app: pingcap-clinic
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["pingcap.com"]
    resources: ["tidbclusters", "tidbmonitors"]
    verbs: ["get", "list"]
  {{- if eq .Values.diag.tlsEnabled true}}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.diag.serviceAccount  | default "pingcap-clinic" }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.diag.clinicRole | default "pingcap-clinic" }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}