# Default values for diag.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# timezone is the default system timzone
timezone: UTC

# diag image config
image:
  diagImage: pingcap/diag
  imageTag: latest
  
  imagePullPolicy: IfNotPresent

# diag-collector pod config
diag:
  diagName: diag-collector
  clinicToken: ""

  # replicaCount: 1

  app: pingcap-clinic

  serviceAccount: pingcap-clinic
  serviceAccountName: pingcap-clinic
  clusterRole: pingcap-clinic

  secretName: pingcap-clinic-cert
  pingcapCrt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1VENDQXMyZ0F3SUJBZ0lRRU1KN3lwaVcrdkZ6b09jamxxNDNsREFOQmdrcWhraUc5dzBCQVFzRkFEQmYKTVFzd0NRWURWUVFHRXdKRFRqRVFNQTRHQTFVRUNnd0hjR2x1WjJOaGNERU5NQXNHQTFVRUN3d0VkR2xrWWpFTwpNQXdHQTFVRUNBd0ZRMmhwYm1FeERUQUxCZ05WQkFNTUJFTkJJREV4RURBT0JnTlZCQWNNQjJOb1pXNW5aSFV3CkhoY05NakV4TURFek1ESXdOek14V2hjTk1qSXhNREV6TURNd056TXhXakFoTVJBd0RnWURWUVFLRXdkUWFXNW4KUTBGUU1RMHdDd1lEVlFRREV3UjBaWE4wTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBeGNMdVR4cE9iNGhJcWJBaFFITFZ1ZXVYSGJNTTRLSUxVYnI1YlpNcFhvY2xBdGVKQlJvSm9IMDlWTnM2CnJ5cENZbHk2Uk0xWUNiSEFjNC9PN043elJlaFhaSjh4dldrSC9keDlGaWtCRjAwWVc4UG1vY2Z2TTRkYUF5TzIKNzJ0RGlQYk56SkdkQW9OenZmMnhmUElFcGs4YlVQeUQyYlA1bEthQ2x6SWpVcU11VmNiTjdlRGJvYTF0WFV0YQp3UDFXQXZpUmZYcFNkc2ZkbSsyVTJMMXBSUlJOTDNwYVZYa2R5WS9vV3BPMHVhUFBCY1pQbkpMcEY5eFkzeCsxCkJJQnNic1ExRUJndndXNmxCSTBtN0JIQW1VUzFWMVU0NGJYditJVTVFY2pRZHRYY3FwNkxKdU1raDNob1JxWnQKOVJ2YmcwSVAxZVhTUUFVOVgza1lVcDF5WlFJREFRQUJvNEhhTUlIWE1Gc0dBMVVkRVFSVU1GS0NPR05zYVc1cApZeTFwYm1keVpYTnpMVFkzT1RRd09UTTROeTVqYmkxdWIzSjBhQzB4TG1Wc1lpNWhiV0Y2YjI1aGQzTXVZMjl0CkxtTnVod1IvQUFBQmh4QUFBQUFBQUFBQUFBQUFBQUFBQUFBQk1Ba0dBMVVkRXdRQ01BQXdId1lEVlIwakJCZ3cKRm9BVUUvM0VFeVhtNUJTNG9mS29UUjE1WGh5TVJmWXdIUVlEVlIwT0JCWUVGRmpaSVFuVmxTcklNOStaajUxZgpJYVNVS2xEWE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCCkJRVUhBd0l3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUM2dVhzYlg2V1h6MVdmTDBpdU9aTC9QNDVBMUYzV0UKazVha21SM2xVYWJITzVYcFVDUkQrV09JL1FHYytNRjYxMFEycDlQcUIzVUhZTUdHdm9qZVBaZTQ1U2UxRzRXVwpuV3puM2QzUEtwZHgvaG1zc2UzSUMyWkNLMG54cnFjZ3pTcmN2Nk9lTEc0OTZFamhLM0tqTjFBbWgxcjVGU1dkCnhoZmVBMXZzUmoxaXBJSmdObVU0QlRxSjF6T2N6VFg3M1g4RmxDbHFOZzNwMS9CWVhSUU1tNWJaSGFmUTJTcEIKT1ZoSXRXMkxtVlE0WE5FdlkzODJKSVk4MlZnU1AwalIvSmVjM0Y1NGx6dndCUnV1NlJzS0I4NkFiTmlpa2tEdQpma1l2aWcyZFNqUk4zckpoTThzNnFvMVNoRlI3QUVGNDBnY242Z01RT2V2d2VnMzFSNEpGVGZJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==


  # We usually recommend not to specify default resources and to leave this as a conscious
  volume: {}
  # if you do not want to lose the data collected by diag-collector due to service restart
  # you can configure the PVC. uncomment the following lines,
  # adjust them as necessary, and remove the curly braces after 'volume:'.
  #  persistentVolumeClaim:
  #    claimName: local-storage-diag

  resources: {}
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  


# diag-api config
service:
  serviceName: diag-api
  type: NodePort
  sessionAffinity: None
  protocol: TCP

  # SecurityContext is security config of this component, it will set template.spec.securityContext
  # Refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context
  securityContext: {}
  # runAsUser: 1000
  # runAsGroup: 2000
  # fsGroup: 2000
  # PodAnnotations will set template.metadata.annotations
  # Refer to https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}





autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
