package bootstrap

import (
	"os"

	"github.com/BurntSushi/toml"
	log "github.com/sirupsen/logrus"
)

const defaultConfig = `# This is the default config file generated by tidb-foresight

[user]
name = "test"
password = "bbc"

[admin]
name = "test"
password = "bbc"

[log]
interval = 600		# 5min
bwlimit = 10		# KB/s
`

type ForesightConfig struct {
	Home    string
	Address string

	User struct {
		Name string `toml:"name"`
		Pass string `toml:"password"`
	} `toml:"user"`

	Admin struct {
		Name string `toml:"name"`
		Pass string `toml:"password"`
	} `toml:"admin"`

	Log struct {
		Interval int `toml:"interval`
		Bwlimit  int `toml:"bwlimit`
	} `toml:"log"`
}

func initConfig(path string) *ForesightConfig {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		log.Warn("config file ", path, " not found, a default one will be generated")

		f, err := os.Create(path)
		if err != nil {
			log.Panic("create default config file failed: ", err)
		}
		defer f.Close()

		if _, err = f.WriteString(defaultConfig); err != nil {
			log.Panic("error occurs while generate default config: ", err)
		}

		if err = f.Sync(); err != nil {
			log.Panic("error occurs while sync default config: ", err)
		}
	}

	config := &ForesightConfig{}
	if _, err := toml.DecodeFile(path, config); err != nil {
		log.Panic("parse config failed: ", err)
	}

	return config
}
